// This file is generated by Slice Machine. Update with care!

import CallToActionSlice from './CallToActionSlice';
import ExampleSlice from './ExampleSlice';
import ExploreSlice from './ExploreSlice';
import IntroductionSlice from './IntroductionSlice';
import QuoteSlice from './QuoteSlice';
import TestimonialSlice from './TestimonialSlice';
import VideoSlice from './VideoSlice';

export {
	CallToActionSlice,
	ExampleSlice,
	ExploreSlice,
	IntroductionSlice,
	QuoteSlice,
	TestimonialSlice,
	VideoSlice,
};

export const components = {
	call_to_action_slice: CallToActionSlice,
	example_slice: ExampleSlice,
	explore_slice: ExploreSlice,
	introduction_slice: IntroductionSlice,
	quote_slice: QuoteSlice,
	testimonial_slice: TestimonialSlice,
	video_slice: VideoSlice,
};
